### ISSUE TITLE
Toolbar icon is not visible (even under customize) on Firefox 58.0.2

### ISSUE THREAD

**Issue by torevor** [prodigion/QuickTabs#2]
I'm running this addon on Chrome and it works like a charm, but after installing of Firefox, I can't find the icon anywhere, even under Customize Toolbar.

**Comment by prodigion** [comment]
There is no icon for this extension.  All it has is F1/F2 for previous/next tab, and F3 for close tab.

You may be thinking of a different chrome extension (I haven't developed it for Chrome).
